<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AutoRemediator.Domain\AutoRemediator.Domain.csproj" />
    <ProjectReference Include="..\AutoRemediator.Contracts\AutoRemediator.Contracts.csproj" />
    <ProjectReference Include="..\AutoRemediator.Shared\AutoRemediator.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Data.Tables" Version="13.4.6" />
    <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="13.4.6" />
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="13.4.6" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="NuGet.Protocol" Version="7.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
