schema: spec-driven

context: |
  domain: Auto Dependency Remediator
  overview: this will be a tool that will automatically update dependencies and create pull requests
            to address those changes and have an AI loop that will address any breaking changes that may occur due to the dependency updates.
            starting with azure dev ops as the main platform that this will target. There will be a web interface that will allow users to configure 
            the tool and view the status of their dependency updates. The updates will be timed and kicked off by a job, the repos that they update should 
            be configurable and the tool should be able to handle multiple repos at once using a queing system and the ability to scale out to multiple instances of the tool. 
            The tool will start with C# and move on from there.
  tech stack: C#, dotnet10, aspire, azure, azure foundry, microsoft agent framework, azure container apps/jobs, azure dev ops, 
              minimal apis, service workers, azure service bus, azure storage, terraform, podman
  architecture: vertical slice architecture, microservices
  testing: TDD, unit testing (xunit.v3), integration testing, functional testing(playwright)
  pactices: commit after each task and after each feature, use feature branches

# Per-artifact rules (optional)
# Add custom rules for specific artifacts.
# Example:
#   rules:
#     proposal:
#       - Keep proposals under 500 words
#       - Always include a "Non-goals" section
#     tasks:
#       - Break tasks into chunks of max 2 hours
