using AutoRemediator.Shared;

namespace AutoRemediator.Domain;

/// <summary>Where a proposed file change came from, and therefore what a review command does with it.</summary>
public enum ProposedFileOrigin
{
    /// <summary>The planner's manifest edit. Replayed by both rebuild and retry.</summary>
    Manifest,

    /// <summary>Regenerated by restore (e.g. <c>packages.lock.json</c>). Recomputed by both rebuild and retry.</summary>
    LockFile,

    /// <summary>A source edit the AI loop contributed. Replayed by rebuild, dropped by retry.</summary>
    AgentEdit,
}

/// <summary>
/// One file in a <see cref="ChangeProposal"/>. <see cref="OriginalContent"/> is the content at the
/// proposal's <see cref="ChangeProposal.BaseCommitId"/>, stored rather than fetched at review time,
/// so review is fast and shows exactly what was compared at verification.
/// </summary>
public sealed record ProposedFile(
    string Path,
    string? OriginalContent,
    string NewContent,
    ProposedFileOrigin Origin);

/// <summary>
/// A verified, AI-repaired change held for a human decision. One per run; at most one active per
/// repository, an invariant kept by the scheduler skip rather than by a storage constraint.
/// </summary>
public sealed record ChangeProposal
{
    public ChangeProposal(
        Guid runId,
        Guid repositoryId,
        string baseCommitId,
        DateTimeOffset verifiedAtUtc,
        IReadOnlyList<ProposedFile> files,
        IReadOnlyList<VerificationDiagnostic> provokingDiagnostics,
        int attempts,
        string? transcriptReference)
    {
        RunId = runId;
        RepositoryId = repositoryId;
        BaseCommitId = Guard.AgainstNullOrWhiteSpace(baseCommitId);
        VerifiedAtUtc = verifiedAtUtc;
        Files = files is { Count: > 0 }
            ? files
            : throw new ArgumentException("A change proposal must carry at least one file.", nameof(files));

        if (Files.All(f => f.Origin != ProposedFileOrigin.AgentEdit))
        {
            throw new ArgumentException(
                "A change proposal must contain at least one agent-authored edit.", nameof(files));
        }

        if (Files.Select(f => f.Path).Distinct().Count() != Files.Count)
        {
            throw new ArgumentException("File paths within a change proposal must be unique.", nameof(files));
        }

        Attempts = attempts > 0
            ? attempts
            : throw new ArgumentOutOfRangeException(nameof(attempts), attempts, "A change proposal exists only because the agent contributed at least one attempt.");

        ProvokingDiagnostics = provokingDiagnostics ?? [];
        TranscriptReference = transcriptReference;
    }

    public Guid RunId { get; }
    public Guid RepositoryId { get; }
    public string BaseCommitId { get; }
    public DateTimeOffset VerifiedAtUtc { get; }
    public IReadOnlyList<ProposedFile> Files { get; }
    public IReadOnlyList<VerificationDiagnostic> ProvokingDiagnostics { get; }
    public int Attempts { get; }
    public string? TranscriptReference { get; }

    /// <summary>The source edits the loop contributed. What rebuild replays and retry drops.</summary>
    public IReadOnlyList<ProposedFile> AgentEdits =>
        Files.Where(f => f.Origin == ProposedFileOrigin.AgentEdit).ToList();

    /// <summary>The planner's manifest edits. Enough, with the run's <see cref="DependencyUpdate"/> list, to reconstruct the update plan.</summary>
    public IReadOnlyList<ProposedFile> ManifestEdits =>
        Files.Where(f => f.Origin == ProposedFileOrigin.Manifest).ToList();
}
